### ISSUE TITLE
Can't seem to be able to decode these

### ISSUE THREAD

**Issue by josegomez** [sqrldev/sqrl-test-vectors#11]
Probably something obvious i'm missing but while trying to decode these back into byte arrays I've had no luck with 3 different libraries. Which leads me to believe is not the libraries but maybe something I'm missing.
Any reason why I can't just invoke base64decode on these strings?

**Comment by alexhauser** [comment]
You have to use urlsafe base64 decoding/encoding!

**Comment by josegomez** [comment]
I was using UrlSafe apparently for the LibSodium, it is UrlSafeNoPadding 
https://libsodium.gitbook.io/doc/helpers#base64-encoding-decoding
sodium_base64_VARIANT_URLSAFE_NO_PADDING

Thanks!!!!
