### ISSUE TITLE
Complement identity vectors

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/sqrl-test-vectors#6]
The identity vectors could be extended with 

- IUK
- ILK

so that the whole identity key generation chain of `IUK -> IMK / ILK -> IDK` can be reproduced and verified.  I think this would be a nice addition, essentially creating a one-stop-shop for verifying all identity-related keys.

Of course, this would mean that we'd have to change all the vectors, since everything would then have to be based off of the IUK values. I could easily create such an updated file, but we'd have to re-verify everything then.

Opinions?

**Comment by shanedk** [comment]
I think we need to keep these things as isolated as possible. If someone runs the vectors and they fail, how are they supposed to know what went wrong? This is the reason for things like "DomainsAreLowercase.net", so that the developer isn't left scratching his head without a clue. It also means the developer doesn't have to write every function before he can test them.

There might be room for vectors covering the entire chain, but I think they should be in addition to these others, something the developer can do at the end to make sure everything works, not while working on the individual pieces.

**Comment by alexhauser** [comment]
>I think we need to keep these things as isolated as possible. If someone runs the vectors and they fail, how are they supposed to know what went wrong?

Adding IUK and ILK would not change anything in that regard. If a dev only wants to verify IDK creation, he would just ignore IUK and ILK. If just IUK->IMK derivation is interesting, just ignore all the other fields.

>This is the reason for things like "DomainsAreLowercase.net", so that the developer isn't left scratching his head without a clue. It also means the developer doesn't have to write every function before he can test them.

All of this would stay exactly the same.

>There might be room for vectors covering the entire chain, but I think they should be in addition to these others, something the developer can do at the end to make sure everything works, not while working on the individual pieces.

Both approaches would be possible with a "complete" file. Just use the information you need and ignore the rest. 

Imo, it would make sense to have all identity-related fields available in one file, but if you prefer splitting it up, that's fine, too. But then I would suggest renaming `identity-vectors.txt` to `idk-vectors.txt`.

**Comment by shanedk** [comment]
So really, you're just talking about making the input the IUK and deriving the IMK from that, while adding in the ILK? That would be fairly straightforward.

**Comment by alexhauser** [comment]
Yes, but changing the IMKs will of course also change the IDKs, hence the need to re-verify (which is annoying).

I don't know, maybe it would indeed be better to create a separate file at this point.

**Comment by shanedk** [comment]
See what I have up there. If you think it needs to be a separate file, we can revert, otherwise if you can verify it I'll close this issue.

**Comment by alexhauser** [comment]
Yep Shane, that looks exactly like what I've had in mind.
I'll try to verify those asap.

**Comment by alexhauser** [comment]
@shanedk, everything verifies just fine, **except for the ILK**. I'll have to investigate a little further to see if the problem is on my end or not.

For the future, I would suggest to handle those kind of things in a pull request instead of directly updating master, it makes it easier to review and comment on, and we don't run the risk of having unverified (and possibly faulty) files in the public repo.

**Comment by shanedk** [comment]
Good idea. I've checked my code, and it looks fine. It seems straightforward since the ILK is just the public key version of the IUK. I don't know why that wouldn't work when the IDK did.

**Comment by alexhauser** [comment]
Shane, I've just exported an identity from the GRC client as text (so rescue code only) and imported it into IdTool, effectively creating the whole block 1 from scratch, thus generating IMK and ILK using my implementation. Then, I compared that ILK to the one in the original identity from the GRC client, and they are identical. So I am at this point pretty sure that my implementation is producing correct results.

The spec says that `IdentityLock := MakePublic( IdentityUnlock )`, and later states that `The “MakePublic” function appearing above uses the “crypto_scalarmult_base” function from LibSodium to create a Diffie-Hellman public key from a private key:`

Hence, my implementation looks like this:

```C++
QByteArray CryptUtil::createIlkFromIuk(QByteArray decryptedIuk)
{
    QByteArray ilk(32, 0);

    crypto_scalarmult_base(reinterpret_cast<unsigned char*>(ilk.data()),
                           reinterpret_cast<const unsigned char*>(decryptedIuk.constData()));

    return ilk;
}
```
Any thoughts?

**Comment by shanedk** [comment]
This could be an issue. I'm using PyNaCl and it doesn't seem to have that function.

**Comment by alexhauser** [comment]
Shane, I'm sure you'll find a solution. In the meantime, I have posted a PR with the fixes for the ILK values. These can also be confirmed using Paul Farrer's `SqrlVect` tool, so we should be good.

**Comment by shanedk** [comment]
Thanks!
